name: Tag Cut Version PR's

on:
    pull_request:
        branches: ["master"]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    if_merged:
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - run: |
                  BRANCH_NAME="${{ github.head_ref }}"
                  echo VERSION NUMBER IS ${BRANCH_NAME##*-}
